theme: jekyll-theme-time-machine
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Clerical biographies in early modern Mainz
description: maps created for the DigiKAR project seminar 2022
