var json_ChristophRudolfvonStadion_13 = {
"type": "FeatureCollection",
"name": "ChristophRudolfvonStadion_13",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 44.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "24.09.1657", "event_end": "#", "display_date": "1657", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 45.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "08.03.1685", "event_end": "#", "display_date": "1685", "event_type": "Wahl", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 46.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "10.01.1695", "event_end": "#", "display_date": "1695", "event_type": "Resignation", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 47.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "10.01.1695", "event_end": "#", "display_date": "1695", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 48.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "17.01.1700", "event_end": "#", "display_date": "1700", "event_type": "Tod", "pers_function": "#", "inst_name": "", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 49.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "17.01.1700", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "1700", "event_type": "Beisetzung", "pers_function": "#", "inst_name": "", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 50.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "13.11.1669", "event_end": "#", "display_date": "1669", "event_type": "Ernennung", "pers_function": "Generalvikar", "inst_name": "Erzbistum Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 51.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "1678", "event_end": "#", "display_date": "1678", "event_type": "Amtsniederlegung", "pers_function": "Generalvikar", "inst_name": "Erzbistum Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 156.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Ernennung", "pers_function": "Statthalter zu Erfurt", "inst_name": "Erzstift Mainz", "place_name": "Erfurt", "place_count": 5.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 11.0298799, 50.9847679 ] } },
{ "type": "Feature", "properties": { "FIELD1": 157.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "1699", "event_end": "#", "display_date": "1699", "event_type": "Ernennung", "pers_function": "Rector magnificus", "inst_name": "#", "place_name": "Erfurt", "place_count": 5.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 11.0298799, 50.9847679 ] } },
{ "type": "Feature", "properties": { "FIELD1": 169.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "30.12.1638", "event_end": "#", "display_date": "1638", "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 170.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "1664", "event_start": "#", "event_end": "#", "display_date": "1664", "event_type": "Studium", "pers_function": "Student", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 171.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "1664", "event_start": "#", "event_end": "#", "display_date": "1664", "event_type": "Weihe", "pers_function": "Niedere Weihen", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 172.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "1669", "event_start": "#", "event_end": "#", "display_date": "1669", "event_type": "Weihe", "pers_function": "Priester", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 195.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "1679", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "1679", "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzstift Mainz", "place_name": "Wien", "place_count": 2.0, "country": "Austria" }, "geometry": { "type": "Point", "coordinates": [ 16.3686303, 48.1975454 ] } },
{ "type": "Feature", "properties": { "FIELD1": 206.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Ernennung", "pers_function": "Geheimrat", "inst_name": "Erzstift Mainz", "place_name": "Mainz", "place_count": 14.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2698184, 50.0069542 ] } },
{ "type": "Feature", "properties": { "FIELD1": 207.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "1679", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "1679", "event_type": "Ernennung", "pers_function": "Hofratspräsident", "inst_name": "Erzstift Mainz", "place_name": "Mainz", "place_count": 14.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2698184, 50.0069542 ] } },
{ "type": "Feature", "properties": { "FIELD1": 259.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "1665", "event_before-date": "1674", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift Mariengreden", "place_name": "Mainz", "place_count": 3.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 263.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift St. Alban", "place_name": "Mainz", "place_count": 7.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 264.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "", "event_end": "#", "display_date": "1675", "event_type": "Wahl", "pers_function": "Probst", "inst_name": "Stift St. Alban", "place_name": "Mainz", "place_count": 7.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 270.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "02.08.1674", "event_end": "#", "display_date": "1674", "event_type": "Wahl", "pers_function": "Probst", "inst_name": "Stift St. Bartholomäus", "place_name": "Frankfurt", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.4934583, 50.0945254 ] } },
{ "type": "Feature", "properties": { "FIELD1": 273.0, "pers_name": "Christoph Rudolf von Stadion", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift St. Ferrutius", "place_name": "Bleidenstadt", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.13748, 50.139647 ] } }
]
}
