var json_DamianFriedrichvonderLeyenHohengeroldseck_12 = {
"type": "FeatureCollection",
"name": "DamianFriedrichvonderLeyenHohengeroldseck_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 2.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Beisetzung", "pers_function": "", "inst_name": "", "place_name": "Würzburg", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9469374, 49.7966264 ] } },
{ "type": "Feature", "properties": { "FIELD1": 22.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1754", "event_end": "#", "display_date": "1754", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Bamberg", "place_name": "Bamberg", "place_count": 4.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.882515, 49.8907746 ] } },
{ "type": "Feature", "properties": { "FIELD1": 23.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "19.02.1755", "event_end": "#", "display_date": "1755", "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Bamberg", "place_name": "Bamberg", "place_count": 4.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.882515, 49.8907746 ] } },
{ "type": "Feature", "properties": { "FIELD1": 52.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "10.01.1755", "event_end": "#", "display_date": "1755", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 53.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "24.09.1781", "event_end": "#", "display_date": "1781", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 54.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1781", "event_end": "#", "display_date": "1781", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 55.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1771", "event_end": "1774\/ 75", "display_date": "1771", "event_type": "Ernennung", "pers_function": "Generalvikar", "inst_name": "#", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 118.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1749", "event_end": "#", "display_date": "1749", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Trier", "place_name": "Trier", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6434155, 49.7562639 ] } },
{ "type": "Feature", "properties": { "FIELD1": 130.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1793", "event_end": "#", "display_date": "1793", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Worms", "place_name": "Worms", "place_count": 6.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.3507182, 49.6341372 ] } },
{ "type": "Feature", "properties": { "FIELD1": 131.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1793", "event_end": "#", "display_date": "1793", "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Worms", "place_name": "Worms", "place_count": 6.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.3507182, 49.6341372 ] } },
{ "type": "Feature", "properties": { "FIELD1": 139.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "01.02.1755", "event_end": "#", "display_date": "1755", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Würzburg", "place_name": "Würzburg", "place_count": 15.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9325575, 49.7933488 ] } },
{ "type": "Feature", "properties": { "FIELD1": 140.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "19.02.1755", "event_end": "#", "display_date": "1755", "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Würzburg", "place_name": "Würzburg", "place_count": 15.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9325575, 49.7933488 ] } },
{ "type": "Feature", "properties": { "FIELD1": 141.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1781", "event_end": "#", "display_date": "1781", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Würzburg", "place_name": "Würzburg", "place_count": 15.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9325575, 49.7933488 ] } },
{ "type": "Feature", "properties": { "FIELD1": 142.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1784", "event_end": "#", "display_date": "1784", "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Würzburg", "place_name": "Würzburg", "place_count": 15.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9325575, 49.7933488 ] } },
{ "type": "Feature", "properties": { "FIELD1": 173.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "03.01.1738", "event_end": "#", "display_date": "1738", "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 204.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "1754", "event_end": "#", "display_date": "1754", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Köln", "place_name": "Köln", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.9582814, 50.9412784 ] } },
{ "type": "Feature", "properties": { "FIELD1": 208.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Ernennung", "pers_function": "Geheimrat", "inst_name": "Erzstift Mainz", "place_name": "Mainz", "place_count": 14.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2698184, 50.0069542 ] } },
{ "type": "Feature", "properties": { "FIELD1": 225.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Ernennung", "pers_function": "Ehrenritter des Malteserorden", "inst_name": "#", "place_name": "Mainz", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 287.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Studium", "pers_function": "Student", "inst_name": "Universität Bamberg", "place_name": "Bamberg", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.886138, 49.8938345 ] } },
{ "type": "Feature", "properties": { "FIELD1": 288.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Studium", "pers_function": "Student", "inst_name": "Universität Freiburg", "place_name": "Freiburg", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.8459496, 47.9935441 ] } },
{ "type": "Feature", "properties": { "FIELD1": 289.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Studium", "pers_function": "Student", "inst_name": "Universität Heidelberg", "place_name": "Heidelberg", "place_count": 2.0, "country": "Gernany" }, "geometry": { "type": "Point", "coordinates": [ 8.6724335, 49.3987524 ] } },
{ "type": "Feature", "properties": { "FIELD1": 300.0, "pers_name": "Damian Friedrich von der Leyen-Hohengeroldseck", "event_after-date": "#", "event_before-date": "#", "event_start": "08.09.1817", "event_end": "#", "display_date": "1817", "event_type": "Tod", "pers_function": "#", "inst_name": "#", "place_name": "Würzburg", "place_count": 3.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9533548, 49.7913044 ] } }
]
}
