var json_HeinrichFerdinandvonderLeyen_10 = {
"type": "FeatureCollection",
"name": "HeinrichFerdinandvonderLeyen_10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 5.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "15.12.1689", "event_end": "24.01.1690", "display_date": 1689.0, "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzbistum Trier", "place_name": "Augsburg", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.89779, 48.3705449 ] } },
{ "type": "Feature", "properties": { "FIELD1": 26.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "02.06.1656", "event_end": "#", "display_date": 1656.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Eichstätt", "place_name": "Eichstätt", "place_count": 9.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 11.1835667, 48.8919581 ] } },
{ "type": "Feature", "properties": { "FIELD1": 27.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "1705", "event_end": "#", "display_date": 1705.0, "event_type": "Resignation und Ablehnung der Wahl zum Fürstbischof", "pers_function": "Bischof", "inst_name": "", "place_name": "Eichstätt", "place_count": 9.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 11.1835667, 48.8919581 ] } },
{ "type": "Feature", "properties": { "FIELD1": 58.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "02.12.1664", "event_end": "#", "display_date": 1664.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 59.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "16.02.1700", "event_end": "#", "display_date": 1700.0, "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 60.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "08.03.1714", "event_end": "#", "display_date": 1714.0, "event_type": "Tod", "pers_function": "#", "inst_name": "", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 61.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "08.03.1714", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": 1714.0, "event_type": "Beisetzung", "pers_function": "#", "inst_name": "Dom Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 119.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "09.07.1653", "event_end": "#", "display_date": 1653.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Trier", "place_name": "Trier", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6434155, 49.7562639 ] } },
{ "type": "Feature", "properties": { "FIELD1": 153.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "14.01.1705", "event_end": "#", "display_date": 1705.0, "event_type": "Wahl", "pers_function": "Fürstbischof", "inst_name": "Bistum Eichstätt", "place_name": "Eichstätt", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 11.185239, 48.8910779 ] } },
{ "type": "Feature", "properties": { "FIELD1": 154.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "16.02.1691", "event_end": "08.06.1691", "display_date": 1691.0, "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzbistum Trier", "place_name": "England", "place_count": 2.0, "country": "United Kingdom" }, "geometry": { "type": "Point", "coordinates": [ -1.1743197, 52.3555177 ] } },
{ "type": "Feature", "properties": { "FIELD1": 162.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "29.03.1682", "event_end": "08.01.1683", "display_date": 1682.0, "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzbistum Trier", "place_name": "Frankfurt", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.6821267, 50.1109221 ] } },
{ "type": "Feature", "properties": { "FIELD1": 196.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "08.03.1676", "event_end": "25.02.1677", "display_date": 1676.0, "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzbistum Trier", "place_name": "Wien", "place_count": 2.0, "country": "Austria" }, "geometry": { "type": "Point", "coordinates": [ 16.3686303, 48.1975454 ] } },
{ "type": "Feature", "properties": { "FIELD1": 197.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "26.01.1679", "event_end": "#", "display_date": 1679.0, "event_type": "Ernennung", "pers_function": "Archidiakon", "inst_name": "Erzbistum Trier", "place_name": "Karden an der Mosel", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.3028282, 50.1723814 ] } },
{ "type": "Feature", "properties": { "FIELD1": 202.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "31.03.1642", "event_end": "#", "display_date": 1642.0, "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "Köln", "place_count": 5.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.9602786, 50.937531 ] } },
{ "type": "Feature", "properties": { "FIELD1": 203.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "1653", "event_start": "#", "event_end": "#", "display_date": 1653.0, "event_type": "Schulbesuch", "pers_function": "#", "inst_name": "#", "place_name": "Köln", "place_count": 5.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.9602786, 50.937531 ] } },
{ "type": "Feature", "properties": { "FIELD1": 248.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "04.08.1673", "event_end": "#", "display_date": 1673.0, "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzbistum Trier", "place_name": "Regensburg", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 12.1016236, 49.0134297 ] } },
{ "type": "Feature", "properties": { "FIELD1": 252.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "12.11.1667", "event_end": "#", "display_date": 1667.0, "event_type": "Gesandtschaft", "pers_function": "Gesandter", "inst_name": "Erzbistum Trier", "place_name": "Rom", "place_count": 2.0, "country": "Italy" }, "geometry": { "type": "Point", "coordinates": [ 12.4963655, 41.9027835 ] } },
{ "type": "Feature", "properties": { "FIELD1": 277.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "#", "event_start": "26.01.1679", "event_end": "#", "display_date": 1679.0, "event_type": "Ernennung", "pers_function": "Probst", "inst_name": "Stift St. Kastor", "place_name": "Karden an der Mosel", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.3013025, 50.183648 ] } },
{ "type": "Feature", "properties": { "FIELD1": 284.0, "pers_name": "Heinrich Ferdinand von der Leyen", "event_after-date": "#", "event_before-date": "1653", "event_start": "#", "event_end": "#", "display_date": 1653.0, "event_type": "Schulbesuch", "pers_function": "Schüler", "inst_name": "#", "place_name": "Trier", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6371433, 49.749992 ] } }
]
}
