var json_HeinrichWilhelmHarffvonDreyborn_9 = {
"type": "FeatureCollection",
"name": "HeinrichWilhelmHarffvonDreyborn_9",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 8.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "1770", "event_start": "#", "event_end": "1780", "display_date": 1770.0, "event_type": "Amtsausübung", "pers_function": "Vicedominus", "inst_name": "#", "place_name": "Bingen", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.904596, 49.9667396 ] } },
{ "type": "Feature", "properties": { "FIELD1": 36.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "18.04.1741", "event_end": "#", "display_date": 1741.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Hildesheim", "place_name": "Hildesheim", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9471512, 52.1490222 ] } },
{ "type": "Feature", "properties": { "FIELD1": 37.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "Dez. 1749", "event_before-date": "Jan. 1750", "event_start": "#", "event_end": "#", "display_date": 1749.0, "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Hildesheim", "place_name": "Hildesheim", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9471512, 52.1490222 ] } },
{ "type": "Feature", "properties": { "FIELD1": 62.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "25.05.1735", "event_end": "#", "display_date": 1735.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 63.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "26.07.1779", "event_end": "#", "display_date": 1779.0, "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 64.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "04.08.1779", "event_end": "#", "display_date": 1779.0, "event_type": "Konfirmation", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 120.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "1745", "event_end": "#", "display_date": 1745.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Trier", "place_name": "Trier", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6434155, 49.7562639 ] } },
{ "type": "Feature", "properties": { "FIELD1": 121.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "1775", "event_end": "#", "display_date": 1758.0, "event_type": "Resignation", "pers_function": "#", "inst_name": "Domkapitel Trier", "place_name": "Trier", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6434155, 49.7562639 ] } },
{ "type": "Feature", "properties": { "FIELD1": 174.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "22.09.1715", "event_end": "#", "display_date": 1715.0, "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 175.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "24.09.1715", "event_end": "#", "display_date": 1715.0, "event_type": "Taufe", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 176.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "#", "event_start": "24.08.1781", "event_end": "#", "display_date": 1781.0, "event_type": "Tod", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 236.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "1770", "event_start": "#", "event_end": "#", "display_date": 1770.0, "event_type": "Wahl", "pers_function": "Probst", "inst_name": "Stift St. Martin. Donat und Nazarius", "place_name": "Mockstadt", "place_count": 1.0, "country": "#" }, "geometry": { "type": "Point", "coordinates": [ 8.9626376, 50.3462735 ] } },
{ "type": "Feature", "properties": { "FIELD1": 250.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "1777", "event_before-date": "1781", "event_start": "#", "event_end": "#", "display_date": 1777.0, "event_type": "Ernennung", "pers_function": "Archidiakon", "inst_name": "Erzbistum Mainz", "place_name": "Rheingau", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 260.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "", "event_before-date": "1775", "event_start": "", "event_end": "", "display_date": null, "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift Mariengreden", "place_name": "Mainz", "place_count": 3.0, "country": "" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 279.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "1778", "event_start": "#", "event_end": "#", "display_date": 1778.0, "event_type": "Wahl", "pers_function": "Stiftsprobst", "inst_name": "Stift St. Mauriz", "place_name": "Mainz", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.6546359, 51.9661366 ] } },
{ "type": "Feature", "properties": { "FIELD1": 296.0, "pers_name": "Heinrich Wilhelm Harff von Dreyborn", "event_after-date": "#", "event_before-date": "25.05.1735", "event_start": "#", "event_end": "#", "display_date": 1735.0, "event_type": "Studium", "pers_function": "Student", "inst_name": "Universität Reims", "place_name": "Reims", "place_count": 1.0, "country": "France" }, "geometry": { "type": "Point", "coordinates": [ 4.031696, 49.258329 ] } }
]
}
