var json_HugoWolfgangvonKesselstatt_7 = {
"type": "FeatureCollection",
"name": "HugoWolfgangvonKesselstatt_7",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 35.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1690", "event_end": "#", "display_date": "1690", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Halberstadt", "place_name": "Halberstadt", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 11.0488695, 51.8916475 ] } },
{ "type": "Feature", "properties": { "FIELD1": 38.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1681", "event_end": "#", "display_date": "1681", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Lüttich", "place_name": "Lüttich", "place_count": 2.0, "country": "Belgium" }, "geometry": { "type": "Point", "coordinates": [ 5.5697498, 50.6329586 ] } },
{ "type": "Feature", "properties": { "FIELD1": 39.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1687", "event_end": "#", "display_date": "1687", "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Lüttich", "place_name": "Lüttich", "place_count": 2.0, "country": "Belgium" }, "geometry": { "type": "Point", "coordinates": [ 5.5697498, 50.6329586 ] } },
{ "type": "Feature", "properties": { "FIELD1": 71.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1687", "event_end": "#", "display_date": "1687", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 72.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "22.04.1699", "event_end": "#", "display_date": "1699", "event_type": "Wahl", "pers_function": "Domkantor", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 73.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "18.12.1709", "event_end": "#", "display_date": "#", "event_type": "Resignation", "pers_function": "Domkantor", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 74.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "18.12.1709", "event_end": "#", "display_date": "1709", "event_type": "Wahl", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 75.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "18.09.1724", "event_end": "#", "display_date": "#", "event_type": "Resignation", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 76.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "18.09.1724", "event_end": "#", "display_date": "1724", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 77.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "02.01.1738", "event_start": "#", "event_end": "#", "display_date": "1738", "event_type": "Beisetzung", "pers_function": "#", "inst_name": "Dom Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 179.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1659", "event_end": "#", "display_date": "1659", "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 230.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "02.01.1738", "event_end": "#", "display_date": "1738", "event_type": "Tod", "pers_function": "#", "inst_name": "", "place_name": "Mainz", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 245.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1720", "event_end": "18.12.1720", "display_date": "1720", "event_type": "Amtsausübung", "pers_function": "Kämmerer des weltlichen Gerichts", "inst_name": "Stadt Mainz", "place_name": "Mainz", "place_count": 3.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2769462, 50.0003654 ] } },
{ "type": "Feature", "properties": { "FIELD1": 266.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift St. Alban", "place_name": "Mainz", "place_count": 7.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 274.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift St. Ferrutius Bleidenstadt", "place_name": "Bleidenstadt", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.13748, 50.139647 ] } },
{ "type": "Feature", "properties": { "FIELD1": 292.0, "pers_name": "Hugo Wolfgang von Kesselstatt", "event_after-date": "#", "event_before-date": "#", "event_start": "1676", "event_end": "#", "display_date": "1676", "event_type": "Studium", "pers_function": "Student", "inst_name": "Universität Köln", "place_name": "Köln", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.9602786, 50.937531 ] } }
]
}
