var json_JohannWilhelmWolffMetternichzurGracht_4 = {
"type": "FeatureCollection",
"name": "JohannWilhelmWolffMetternichzurGracht_4",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 18.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "1650", "event_start": "1644", "event_end": "#", "display_date": 1650.0, "event_type": "Studium", "pers_function": "Student", "inst_name": "Collegium Germanicum", "place_name": "Rom", "place_count": 4.0, "country": "Italy" }, "geometry": { "type": "Point", "coordinates": [ 12.4917397, 41.9050908 ] } },
{ "type": "Feature", "properties": { "FIELD1": 85.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "30.09.1630", "event_end": "#", "display_date": 1630.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 86.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "12.11.1674", "event_end": "#", "display_date": 1674.0, "event_type": "Wahl", "pers_function": "Domscholaster", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 87.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "4.11.1679", "event_end": "#", "display_date": 1679.0, "event_type": "Resignation", "pers_function": "Domscholaster", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 88.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "4.11.1679", "event_end": "#", "display_date": 1679.0, "event_type": "Wahl", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 89.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "20.2.1685", "event_end": "#", "display_date": 1685.0, "event_type": "Resignation", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 90.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "20.2.1685", "event_end": "#", "display_date": 1685.0, "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 91.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "17.12.1694", "event_end": "#", "display_date": 1694.0, "event_type": "Beisetzung", "pers_function": "", "inst_name": "Dom Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 109.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "1693", "event_end": "#", "display_date": 1693.0, "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Münster", "place_name": "Münster", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.6257716, 51.9629806 ] } },
{ "type": "Feature", "properties": { "FIELD1": 110.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "1649", "event_end": "#", "display_date": 1649.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Münster", "place_name": "Münster", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.6257716, 51.9629806 ] } },
{ "type": "Feature", "properties": { "FIELD1": 111.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "1644", "event_end": "#", "display_date": 1644.0, "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Paderborn", "place_name": "Paderborn", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.75583, 51.7189529 ] } },
{ "type": "Feature", "properties": { "FIELD1": 182.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "30.11.1624", "event_end": "#", "display_date": 1624.0, "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 183.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "#", "event_start": "15.12.1694", "event_end": "#", "display_date": 1694.0, "event_type": "Tod", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 216.0, "pers_name": "Johann Wilhelm Wolff-Metternich zur Gracht", "event_after-date": "#", "event_before-date": "15.12.1694", "event_start": "#", "event_end": "#", "display_date": 1694.0, "event_type": "Ernennung", "pers_function": "Geheimer Rat", "inst_name": "Erzstift Mainz", "place_name": "Mainz", "place_count": 14.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2698184, 50.0069542 ] } }
]
}
