var json_JohannHeppenheimgenanntvonSaal_6 = {
"type": "FeatureCollection",
"name": "JohannHeppenheimgenanntvonSaal_6",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 1.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1630", "event_end": "#", "display_date": "1630", "event_type": "Studium", "pers_function": "Student", "inst_name": "Albertina", "place_name": "Freiburg", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 7.8421043, 47.9990077 ] } },
{ "type": "Feature", "properties": { "FIELD1": 78.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1636", "event_end": "#", "display_date": "1636", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 79.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "06.02.1653", "event_end": "#", "display_date": "1653", "event_type": "Wahl", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 80.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "17.07.1668", "event_end": "#", "display_date": "1668", "event_type": "Resignation", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 81.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "17.07.1668", "event_end": "#", "display_date": "1668", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 82.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "03.02.1672", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Beisetzung", "pers_function": "#", "inst_name": "Dom Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 132.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1617", "event_end": "#", "display_date": "1617", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Worms", "place_name": "Worms", "place_count": 6.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.3507182, 49.6341372 ] } },
{ "type": "Feature", "properties": { "FIELD1": 133.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1654", "event_end": "#", "display_date": "1654", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Worms", "place_name": "Worms", "place_count": 6.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.3507182, 49.6341372 ] } },
{ "type": "Feature", "properties": { "FIELD1": 143.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "15.10.1622", "event_end": "#", "display_date": "1622", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Würzburg", "place_name": "Würzburg", "place_count": 15.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.9325575, 49.7933488 ] } },
{ "type": "Feature", "properties": { "FIELD1": 180.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1609", "event_end": "#", "display_date": "1609", "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 181.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1619", "event_end": "1626", "display_date": "1619", "event_type": "Schulbesuch", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 215.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1666", "event_end": "#", "display_date": "1666", "event_type": "Vertretung des Kurfürsten während eines Pestausbruches", "pers_function": "#", "inst_name": "Erzstift Mainz", "place_name": "Mainz", "place_count": 14.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2698184, 50.0069542 ] } },
{ "type": "Feature", "properties": { "FIELD1": 231.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "03.02.1672", "event_end": "#", "display_date": "1672", "event_type": "Tod", "pers_function": "#", "inst_name": "#", "place_name": "Mainz", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 238.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "13.05.1653", "event_end": "#", "display_date": "1653", "event_type": "Wahl", "pers_function": "Stiftsprobst", "inst_name": "Stift Neumünster", "place_name": "Würzburg", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 9.931242, 49.7939163 ] } },
{ "type": "Feature", "properties": { "FIELD1": 290.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "1654", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Amtsausübung", "pers_function": "Kanzler", "inst_name": "Universität Heidelberg", "place_name": "Heidelberg", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.6724335, 49.3987524 ] } },
{ "type": "Feature", "properties": { "FIELD1": 295.0, "pers_name": "Johann Heppenheim genannt von Saal", "event_after-date": "#", "event_before-date": "#", "event_start": "1634", "event_end": "#", "display_date": "1634", "event_type": "Studium", "pers_function": "Student", "inst_name": "Universität Perugia", "place_name": "Perugia", "place_count": 1.0, "country": "Italy" }, "geometry": { "type": "Point", "coordinates": [ 12.3868984, 43.1164268 ] } }
]
}
