var json_KarlEmmerichFranzvonBreidbachBrresheim_3 = {
"type": "FeatureCollection",
"name": "KarlEmmerichFranzvonBreidbachBrresheim_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "FIELD1": 19.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "1694", "event_end": "1696", "display_date": "1694", "event_type": "Studium", "pers_function": "Student", "inst_name": "Collegium Germanicum", "place_name": "Rom", "place_count": 4.0, "country": "Italy" }, "geometry": { "type": "Point", "coordinates": [ 12.4917397, 41.9050908 ] } },
{ "type": "Feature", "properties": { "FIELD1": 92.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "27.01.1710", "event_end": "#", "display_date": "1710", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 93.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "9.10.1724", "event_end": "#", "display_date": "1724", "event_type": "Wahl", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 94.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "12.02.1738", "event_end": "#", "display_date": "1738", "event_type": "Wahl", "pers_function": "Domprobst", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 95.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "", "event_before-date": "", "event_start": "12.02.1738", "event_end": "", "display_date": "", "event_type": "Resignation", "pers_function": "Domdekan", "inst_name": "Domkapitel Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 96.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "20.02.1743", "event_before-date": "", "event_start": "", "event_end": "", "display_date": "", "event_type": "Beisetzung", "pers_function": "", "inst_name": "Dom Mainz", "place_name": "Mainz", "place_count": 65.0, "country": "" }, "geometry": { "type": "Point", "coordinates": [ 8.274439126, 49.9989965 ] } },
{ "type": "Feature", "properties": { "FIELD1": 123.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "1687", "event_end": "#", "display_date": "1687", "event_type": "Aufschwörung", "pers_function": "Domherr", "inst_name": "Domkapitel Trier", "place_name": "Trier", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6434155, 49.7562639 ] } },
{ "type": "Feature", "properties": { "FIELD1": 124.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "1714", "event_end": "#", "display_date": "1714", "event_type": "Resignation", "pers_function": "Domherr", "inst_name": "Domkapitel Trier", "place_name": "Trier", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6434155, 49.7562639 ] } },
{ "type": "Feature", "properties": { "FIELD1": 184.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "20.02.1743", "event_end": "#", "display_date": "1743", "event_type": "Tod", "pers_function": "#", "inst_name": "#", "place_name": "#", "place_count": 24.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 10.451526, 51.165691 ] } },
{ "type": "Feature", "properties": { "FIELD1": 232.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "#", "event_end": "#", "display_date": "#", "event_type": "Präsident", "pers_function": "Präsident", "inst_name": "???", "place_name": "Mainz", "place_count": 12.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 246.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "1740", "event_before-date": "", "event_start": "#", "event_end": "#", "display_date": "1740", "event_type": "Amtsausübung", "pers_function": "Geheimer Rat", "inst_name": "Stadt Mainz", "place_name": "Mainz", "place_count": 3.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2769462, 50.0003654 ] } },
{ "type": "Feature", "properties": { "FIELD1": 247.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "1720", "event_end": "1743", "display_date": "1720", "event_type": "Amtsausübung", "pers_function": "Kämmerer des weltlichen Gerichts der Stadt", "inst_name": "Stadt Mainz", "place_name": "Malnz", "place_count": 3.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2769462, 50.0003654 ] } },
{ "type": "Feature", "properties": { "FIELD1": 276.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "", "event_before-date": "", "event_start": "", "event_end": "", "display_date": "", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "St. Ignaz", "place_name": "Mainz", "place_count": 1.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2782727, 49.9956325 ] } },
{ "type": "Feature", "properties": { "FIELD1": 281.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "18.06.1712", "event_end": "#", "display_date": "1712", "event_type": "Aufschwörung", "pers_function": "Stiftsherr", "inst_name": "Stift St. Peter", "place_name": "Mainz", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.26985, 50.004825 ] } },
{ "type": "Feature", "properties": { "FIELD1": 283.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "18.06.1712", "event_end": "#", "display_date": "1712", "event_type": "Wahl", "pers_function": "Dekan", "inst_name": "Stift St.Viktor", "place_name": "Mainz", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 8.2472526, 49.9928617 ] } },
{ "type": "Feature", "properties": { "FIELD1": 285.0, "pers_name": "Karl Emmerich Franz von Breidbach-Bürresheim", "event_after-date": "#", "event_before-date": "#", "event_start": "18.01.1674", "event_end": "#", "display_date": "1674", "event_type": "Geburt", "pers_function": "#", "inst_name": "#", "place_name": "Trier", "place_count": 2.0, "country": "Germany" }, "geometry": { "type": "Point", "coordinates": [ 6.6371433, 49.749992 ] } }
]
}
